### ISSUE TITLE
克劳德无法正常使用

### ISSUE THREAD

**Issue by cyuanyuan520** [mt-altman/cursor2api#1]
大佬您好 ,您的项目cursor2api使用克劳德时会返回奇怪的内容, 无法正常解析, 请问可以解决一下吗? 图片如下
![361e6ea69a90914ef52faa8f21796a3d](https://github.com/user-attachments/assets/5bcef024-137b-41ab-9b51-e51f47592dd8)

**Comment by mt-altman** [comment]
不再维护！！去用这个吧

https://github.com/zhx47/cursor-api
